// Generates a Defence Brief PDF using jsPDF.
// Called from DefenceBrief.jsx after the brief is generated.
// Returns a jsPDF instance (caller calls .save() to download).

import { jsPDF } from 'jspdf';

const PAGE_W    = 210; // A4 mm
const MARGIN    = 20;
const CONTENT_W = PAGE_W - MARGIN * 2;
const LINE_H    = 7;   // mm between lines

function addWrappedText(doc, text, x, y, maxWidth, lineHeight = LINE_H) {
  const lines = doc.splitTextToSize(String(text || ''), maxWidth);
  doc.text(lines, x, y);
  return y + lines.length * lineHeight;
}

function addSectionHeading(doc, label, y, color = [13, 27, 42]) {
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(9);
  doc.setTextColor(...color);
  doc.text(label.toUpperCase(), MARGIN, y);
  doc.setDrawColor(...color);
  doc.setLineWidth(0.3);
  doc.line(MARGIN, y + 1.5, PAGE_W - MARGIN, y + 1.5);
  return y + 8;
}

function checkPageBreak(doc, y, needed = 20) {
  if (y + needed > 277) {
    doc.addPage();
    return MARGIN + 10;
  }
  return y;
}

export function generateDefenceBrief(brief, topic) {
  const doc = new jsPDF({ unit: 'mm', format: 'a4' });

  // ── Header ────────────────────────────────────────────────────────────────
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(20);
  doc.setTextColor(13, 27, 42);
  doc.text('DEFENCE BRIEF', MARGIN, 28);

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10);
  doc.setTextColor(80, 100, 120);
  const topicLine  = topic || 'Your Project';
  const topicLines = doc.splitTextToSize(topicLine, CONTENT_W);
  doc.text(topicLines, MARGIN, 36);

  doc.setFontSize(8);
  doc.setTextColor(160, 170, 180);
  doc.text(
    `Generated by FYPro · ${new Date().toLocaleDateString('en-GB', { day: 'numeric', month: 'long', year: 'numeric' })}`,
    MARGIN,
    36 + topicLines.length * 5 + 2
  );

  // divider
  doc.setDrawColor(0, 102, 255);
  doc.setLineWidth(0.5);
  doc.line(MARGIN, 44, PAGE_W - MARGIN, 44);

  let y = 54;

  // ── Opening Statement ─────────────────────────────────────────────────────
  y = addSectionHeading(doc, 'Opening Statement', y, [0, 102, 255]);
  doc.setFont('helvetica', 'italic');
  doc.setFontSize(10);
  doc.setTextColor(40, 60, 80);
  y = addWrappedText(doc, brief.openingStatement || '', MARGIN, y, CONTENT_W);
  y += 8;

  // ── Weak Spots ────────────────────────────────────────────────────────────
  y = checkPageBreak(doc, y, 30);
  y = addSectionHeading(doc, 'Weak Spots & Model Answers', y, [220, 38, 38]);

  for (const ws of (brief.weakSpots || [])) {
    y = checkPageBreak(doc, y, 30);

    doc.setFont('helvetica', 'bold');
    doc.setFontSize(8);
    const severityColor = ws.severity === 'Critical' ? [220, 38, 38]
      : ws.severity === 'Serious' ? [217, 119, 6]
      : [99, 102, 241];
    doc.setTextColor(...severityColor);
    doc.text(`[${(ws.severity || '').toUpperCase()}]`, MARGIN, y);

    doc.setTextColor(13, 27, 42);
    doc.setFontSize(10);
    doc.text(ws.title || '', MARGIN + 22, y);
    y += 5;

    doc.setFont('helvetica', 'italic');
    doc.setFontSize(9);
    doc.setTextColor(100, 120, 140);
    y = addWrappedText(doc, `"${ws.examiner_question || ''}"`, MARGIN + 3, y, CONTENT_W - 3, 5.5);
    y += 2;

    doc.setFont('helvetica', 'bold');
    doc.setFontSize(8);
    doc.setTextColor(22, 163, 74);
    doc.text('MODEL ANSWER', MARGIN + 3, y);
    y += 5;

    doc.setFont('helvetica', 'normal');
    doc.setFontSize(9.5);
    doc.setTextColor(30, 50, 70);
    y = addWrappedText(doc, ws.studentAnswer || ws.model_answer || '', MARGIN + 3, y, CONTENT_W - 3);
    y += 8;
  }

  // ── Examiner Q&As ─────────────────────────────────────────────────────────
  y = checkPageBreak(doc, y, 30);
  y = addSectionHeading(doc, 'Likely Examiner Questions', y, [217, 119, 6]);

  for (const qa of (brief.examinerQas || [])) {
    y = checkPageBreak(doc, y, 22);

    doc.setFont('helvetica', 'bold');
    doc.setFontSize(9);
    doc.setTextColor(217, 119, 6);
    doc.text(`Q${qa.number}`, MARGIN, y);

    doc.setFont('helvetica', 'italic');
    doc.setFontSize(9.5);
    doc.setTextColor(13, 27, 42);
    y = addWrappedText(doc, qa.question || '', MARGIN + 10, y, CONTENT_W - 10, 5.5);
    y += 2;

    doc.setFont('helvetica', 'normal');
    doc.setFontSize(9);
    doc.setTextColor(60, 80, 100);
    y = addWrappedText(doc, qa.answer || '', MARGIN + 10, y, CONTENT_W - 10, 5.5);
    y += 7;
  }

  // ── Footer ────────────────────────────────────────────────────────────────
  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(7);
    doc.setTextColor(180, 190, 200);
    doc.text(`FYPro Defence Brief · fypro.com.ng · Page ${i} of ${pageCount}`, MARGIN, 290);
  }

  return doc;
}
